TestProject/TestProject/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestProject.Controllers
{
    public class PersonController : Controller
    {

        public PersonController() 
        {
            _personRepository = new Domain.Repository.PersonRepository(new SQLRepository.SQLPersonRepository());
        }

        public ActionResult GetAllPerson()
        {
            var result = _personRepository.GetAllPerson();
            return View(result);
        }

        public ActionResult CreatePerson()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SavePerson(Domain.DTO.Person person)
        {
            var result = _personRepository.CreatePerson(person);
            return RedirectToAction("GetAllPerson");
        }

        public ActionResult UpdatePerson()
        {
            return View();
        }

        public ActionResult RemovePerson(Int32 id)
        {
            var result = _personRepository.RemovePerson(id);
            return RedirectToAction("GetAllPerson");
        }
                
        private Domain.Repository.PersonRepository _personRepository;
    }
}

TestProject/TestProject/Views/Person/CreatePerson.cshtml
@{
    ViewBag.Title = "CreatePerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreatePerson</h2>

<form action="~/Person/SavePerson" method="post">

    <label for="Name">Name:</label>
    <br />
    <input id="Name" name="Name" type="text" value="" />
    <br />
    <br />

    <label for="Email">Email:</label>
    <br />
    <input id="Email" name="Email" type="text" value="" />
    <br />
    <br />

    <label for="DateOfBirth">DateOfBirth:</label>
    <br />
    <input id="DateOfBirth" name="DateOfBirth" type="text" value="" />
    <br />
    <br />

    <input id="create" name="create" type="submit" value="Create" />
</form>

TestProject/TestProject/Views/Person/GetAllPerson.cshtml
@{
    ViewBag.Title = "GetAllPerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<Domain.DTO.Person>

<h2>All Persons</h2>

@if (Model != null && Model.Count() > 0)
{
    foreach (var item in Model)
    {
        <input id="Name" name="Name" type="text" value="@item.Name" />
        <br />
        <input id="Email" name="Email" type="text" value="@item.Email" />
        <br />
        <input id="DateOfBirth" name="DateOfBirth" type="text" value="@item.DateOfBirth" />
        <br />
        <a href="/Person/RemovePerson?id=@item.Id" id="0">Remove Person</a>

        <br />
        <br />
    }
}
else
{
    <div>There are no any data </div>
}
@Html.ActionLink("Create new Person", "CreatePerson", "Person")

TestProject/TestProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>